export const email = '[data-test="username"]'
export const password = '[data-test="password"]'
export const submitButton = '[data-test="login-button"]'
export const succesfullyLoggedIn = '.app_logo'
export const unsuccesfullyLoggedIn = '[data-test="error"]'
export const addToCartSauceLabsBackpack = '[data-test="add-to-cart-sauce-labs-backpack"]'
export const shoppingIcon = '.shopping_cart_link'
export const cartSauceLabsBackpack = '.cart_item'
export const checkout = '[data-test="checkout"]'
export const firstName = '[data-test="firstName"]'
export const lastName = '[data-test="lastName"]'
export const postalCode = '[data-test="postalCode"]'
export const next = '[data-test="continue"]'
export const finish = '[data-test="finish"]'
export const checkoutComplete = '#checkout_complete_container'
export const removeSauceLabsBackpack = '[data-test="remove-sauce-labs-backpack"]'
export const twitterIcon = '.social_twitter > a'
export const facebookIcon = '.social_facebook > a'
export const linkedinIcon = '.social_linkedin > a'